In [2]:
import numpy as np

In [3]:
# 2 - наименьшее манхэттенское расстояние

# a=( -3; -2),  b=( 8; -1), c=( 1; 0) 
a = np.array([-3, -2])
b = np.array([8, -1])
c = np.array([1, 0])


print(np.sum(np.abs(a - b)))
print(np.sum(np.abs(a - c)))
print(np.sum(np.abs(b - c)))

print(np.linalg.norm(a - b, ord = 1))
print(np.linalg.norm(a - c, ord = 1))
print(np.linalg.norm(b - c, ord = 1))

12
6
8
12.0
6.0
8.0


In [4]:
# 3 - наибольшая норма вектора: единичная, квадратичная (евклидова), бесконечная

# a=( -3; 8)

a = np.array([-3, 8])

print(np.linalg.norm(a, ord=1))
print(np.linalg.norm(a, ord=2))
print(np.linalg.norm(a, ord=np.Inf))

11.0
8.54400374531753
8.0


In [5]:
# 5 - косинус ушла между векторами

#  a=( -3,2; -2; 5), b=( 3,4; -3; 2)

a = np.array([-3.2, -2, 5])
b = np.array([3.4, -3, 2])

# np.arccos(a @ a / np.linalg.norm(a) / np.linalg.norm(b)) * 180 / np.pi

a @ b / np.linalg.norm(a) / np.linalg.norm(b)

0.16492681813275975

In [17]:
# 6 - квадрат длины вектора с

# a=( 3,4; -2; 5), b=( -5,0; -3; 2)

a = np.array([3.4, -2, 5])
b = np.array([-5.0, -3, 2])

c = 2*a - 3*b

print(c)
print(np.linalg.norm(c))
print(c[0]**2 + c[1]**2 + c[2]**2)

[21.8  5.   4. ]
22.720915474513784
516.24


In [8]:
# 7 - наибольшая близость профиля покупателя: ядро и евклидово пространство

# bigger is better
# a=(3: 11, 5: 2, 11: 25, 20: 10)
# b=(3: 9, 7: 2, 10: 15, 20: 8)
# c=(3: 21, 6: 2, 11: 5, 20: 17)

from cmath import exp


a = np.array([0, 0, 0, 11, 0, 2, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 10])
b = np.array([0, 0, 0, 9, 0, 0, 0, 2, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8])
c = np.array([0, 0, 0, 21, 0, 0, 2, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 17])

# sim(x, y) = ker(dist(x,y)) = exp(-0.01*dist(x,y)).

dist_ab = np.linalg.norm(a - b, ord=2)
dist_ac = np.linalg.norm(a - c, ord=2)

print(f'AB: {round(np.exp(-0.01 * dist_ab), 2)}')
print(f'AC: {round(np.exp(-0.01 * dist_ac), 2)}')


AB: 0.75
AC: 0.79


In [9]:
# 8 - наибольшая близость профиля покупателя - cosine-similarity

# a=(3: 11, 5: 2, 11: 25, 20: 10)
# b=(3: 6, 7: 2, 10: 15, 20: 10)
# c=(3: 21, 6: 2, 11: 5, 20: 26) 

a = np.array([0, 0, 0, 11, 0, 2, 0, 0, 0, 0, 0, 25, 0, 0, 0, 0, 0, 0, 0, 0, 10])
b = np.array([0, 0, 0, 6, 0, 0, 0, 2, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10])
c = np.array([0, 0, 0, 21, 0, 0, 2, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 26])
# sim(x, y) = cos(x,y).

cos_ab = a @ b / np.linalg.norm(a, ord = 2) / np.linalg.norm(b, ord=2)
cos_ac = a @ c / np.linalg.norm(a, ord = 2) / np.linalg.norm(c, ord=2)

print(round(cos_ab, 2))
print(round(cos_ac, 2))

from sklearn.metrics.pairwise import cosine_similarity as cos_sim
users = np.vstack([a, b, c])
print(np.round(cos_sim(users), 2))


0.3
0.62
[[1.   0.3  0.62]
 [0.3  1.   0.6 ]
 [0.62 0.6  1.  ]]


In [13]:
# 9 - MSE

# (-1.0, 0.0), (0.0, 0.0), (1.0, 1.0), (2.0, 4.0).
# (-1.0, 0.0), (0.0, 0.0), (1.0, 1.0), (2.0, 4.0).
# ym(x)= a0 + a1*x2
# ym(x)= a0 + a1*x2
# (a0, a1) = (-0,5; 1,1).

x_list = np.array([-1, 0, 1, 2])
y_list = np.array([0, 0, 1, 4])

coeffs = np.array([-0.5, 1.1])

# def f(x):
#     return coeffs[0] + coeffs[1] * x**2

y_m = lambda x: coeffs @ np.array([np.ones_like(x), x**2])

y_model = y_m(x_list)

# print(np.array([np.ones_like(x_list), x_list**2]))
print(y_model)

err = y_list - y_model
print(err)

from sklearn.metrics import mean_squared_error
print(f'MSE = {np.mean(err * err)}')

print(f'MSE = {mean_squared_error(y_list, y_model)}')
print(f'MSE = {np.round(mean_squared_error(y_list, y_model),2 )}')

[ 0.6 -0.5  0.6  3.9]
[-0.6  0.5  0.4  0.1]
MSE = 0.19499999999999998
MSE = 0.19499999999999998
MSE = 0.19


In [15]:
# 10 - MAE

# (-1.0, 0.0), (0.0, 0.0), (1.0, 1.0), (2.0, 4.0).
# (-1.0, 0.0), (0.0, 0.0), (1.0, 1.0), (2.0, 4.0).
# ym(x)= a0 + a1*x2
# ym(x)= a0 + a1*x2.
# (a0, a1) = (0,1; 1,1).
# (a0, a1) = (-0,1; 1).

x_list = np.array([-1, 0, 1, 2])
y_list = np.array([0, 0, 1, 4])

coeffs = np.array([-0.1, 1])

# def f(x):
#     return coeffs[0] + coeffs[1] * x**2

y_m = lambda x: coeffs @ np.array([np.ones_like(x), x**2])

y_model = y_m(x_list)

# print(np.array([np.ones_like(x_list), x_list**2]))
print(y_model)

err = y_list - y_model
print(err)

print(f'MAE = {np.mean(np.abs(err))}')


from sklearn.metrics import mean_absolute_error
print(f'MAE = {mean_absolute_error(y_list, y_model)}')
print(f'MAE = {np.round(mean_absolute_error(y_list, y_model), 2)}')

[ 0.9 -0.1  0.9  3.9]
[-0.9  0.1  0.1  0.1]
MAE = 0.30000000000000004
MAE = 0.30000000000000004
MAE = 0.3
