In [4]:
import numpy as np

A = np.array([[1, 1, 1], [2, 2, 2]])
B = np.array([[1, 2, 3], [4, 5, 6]])

print(f'A = \n {A}')
print(f'B = \n {B}')

A = 
 [[1 1 1]
 [2 2 2]]
B = 
 [[1 2 3]
 [4 5 6]]


In [5]:

C = A + B
print(f'A + B = \n {C}')

D = A * B
print(f'A * B = \n {D}')


A + B = 
 [[2 3 4]
 [6 7 8]]
A * B = 
 [[ 1  2  3]
 [ 8 10 12]]


In [7]:
# A + 2
print(f'A + 2 = \n {A + 2}')
# A * 2
print(f'A * 2 = \n {A * 2}')

A + 2 = 
 [[3 3 3]
 [4 4 4]]
A * 2 = 
 [[2 2 2]
 [4 4 4]]


In [14]:
T = np.array([10, 20, 30])
print(f'A + T = \n {A + T}')
print(f'A * T = \n {A * T}')

T = np.array([[10], [20]])

print(f'T = {T}')
print(f'A + T = \n {A + T}')
print(f'A * T = \n {A * T}')


A + T = 
 [[11 21 31]
 [12 22 32]]
A * T = 
 [[10 20 30]
 [20 40 60]]
T = [[10]
 [20]]
A + T = 
 [[11 11 11]
 [22 22 22]]
A * T = 
 [[10 10 10]
 [40 40 40]]


In [21]:
A = np.array([[1, -2], [0, 3], [2, -1]])
B = np.array([[2, 1], [9, -3]])

print(f'A = \n{A}')
print(f'B = \n{B}')

C = A @ B
print(f'A @ B = \n{C}')

A = 
[[ 1 -2]
 [ 0  3]
 [ 2 -1]]
B = 
[[ 2  1]
 [ 9 -3]]
A @ B = 
[[-16   7]
 [ 27  -9]
 [ -5   5]]


In [25]:
# расчет выхода слоя нейронов
# x = np.array([[1], [-1], [2], [3]]) # - формально так, но можно и 
x = np.array([1, -1, 2, 3])
print(f'x = {x}')

W = np.array([[-3, 1, 1, 2], [-5, 2, 1, 1]])
print(f'W = \n {W}')

z = np.dot(W, x)
y = np.sign(z)

print(f'z = {z}')
print(f'y = {y}')



x = [ 1 -1  2  3]
W = 
 [[-3  1  1  2]
 [-5  2  1  1]]
z = [ 4 -2]
y = [ 1 -1]


In [30]:
# practice
W = np.array([[-60, 1, 1, 2, 2, 3],
              [-80, 1, 1, 2, 2, 3]])

x = np.array([1, 10, 8, 7, 6, 5])

z = W @ x
print(z)



[ -1 -21]
