In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [12]:
Query = np.array([14, 0, 0, 6, 30, 0, 62, 10, 0, 7, 7, 0, 0, 0, 2, 3, 15, 15, 9, 0, 0, 10, 0, 5, 5, 0, 0, 5, 45, 4])

SuccessQ = np.array([0, 0, 0, 0, 0, 0, 24, 4, 0, 4, 4, 0, 0, 0, 0, 2, 7, 9, 9, 0, 0, 2, 0, 4, 2, 0, 0, 5, 34, 2])

FailureQ = np.array([14, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 3, 2, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 2])

print(len(Query), len(SuccessQ), len(FailureQ))

t_window = 14
t_step = 2

Q_len = len(Query)

Samples_Q = (Q_len - t_window + 2) // t_step
print(Samples_Q)


def form_window_data(data, t_window, t_step):
    window_list = [data[i : i + t_window] for i in range(0, len(data) - t_window + 2, t_step)]
    return np.array(window_list)

print(Query)
print(form_window_data(Query, t_window, t_step))

Query_w = form_window_data(Query, t_window, t_step)
SuccessQ_w = form_window_data(SuccessQ, t_window, t_step)
FailureQ_w = form_window_data(FailureQ, t_window, t_step)

data = np.concatenate([Query_w[:, :, np.newaxis], SuccessQ_w[:, :, np.newaxis], FailureQ_w[:, :, np.newaxis]], axis=2)

print(data.shape)


30 30 30
9
[14  0  0  6 30  0 62 10  0  7  7  0  0  0  2  3 15 15  9  0  0 10  0  5
  5  0  0  5 45  4]
[[14  0  0  6 30  0 62 10  0  7  7  0  0  0]
 [ 0  6 30  0 62 10  0  7  7  0  0  0  2  3]
 [30  0 62 10  0  7  7  0  0  0  2  3 15 15]
 [62 10  0  7  7  0  0  0  2  3 15 15  9  0]
 [ 0  7  7  0  0  0  2  3 15 15  9  0  0 10]
 [ 7  0  0  0  2  3 15 15  9  0  0 10  0  5]
 [ 0  0  2  3 15 15  9  0  0 10  0  5  5  0]
 [ 2  3 15 15  9  0  0 10  0  5  5  0  0  5]
 [15 15  9  0  0 10  0  5  5  0  0  5 45  4]]
(9, 14, 3)


array([[14,  0,  0,  6, 30,  0, 62, 10,  0,  7,  7,  0,  0,  0],
       [ 0,  6, 30,  0, 62, 10,  0,  7,  7,  0,  0,  0,  2,  3]])

In [18]:
print(data[0:2,:,0])

nonzero_data = data[0, :, 0] > 0
print(nonzero_data)

SuccessQ_prct = 100 * data[0, nonzero_data, 1] / data[0, nonzero_data, 0]
print(np.round(SuccessQ_prct, 2))

[[14  0  0  6 30  0 62 10  0  7  7  0  0  0]
 [ 0  6 30  0 62 10  0  7  7  0  0  0  2  3]]
[ True False False  True  True False  True  True False  True  True False
 False False]
[ 0.    0.    0.   38.71 40.   57.14 57.14]


In [20]:
data2 = np.concatenate([Query_w[:, np.newaxis, :], SuccessQ_w[:, np.newaxis, :], FailureQ_w[:, np.newaxis, :]], axis=1)
print(data2.shape)

(9, 3, 14)
