## Fashion-MNIST

Вам предлагается решить задачу классификации на наборе данных Fashion-MNIST, который вы можете скачать по следующей ссылке [Fashion-MNIST on Kaggle](https://www.kaggle.com/zalando-research/fashionmnist)

Данные проект является учебным и его цель – научиться работать с различными моделями машинного обучения. Вам необязательно строить самую лучшую модель и получать лучшее качество на тестовых данных. Самое важное – это научиться обучать модели и анализировать полученные результаты. В результате, вы научитесь использовать и подготавливать данные для решения задачи классификации. Так же вы изучите на практике различные алгоритмы машиного обучения, такие как логистическая регрессия, полносвязные нейронные сети и сверточные нейронные сети. Более того, вы научитесь обучать эти модели и анализировать результаты работы этих алгоритмов на новых данных

Fashion-MNIST – это датасет состоящий из 70000 черно-белых изображений одежды 28х28 пикселей каждое. 60000 из них содержатся в тренировочной выборке, и 10000 – в тестовой. Этот набор данных представляет из себя альтернативу обычному датасету рукописных цифр MNIST. Существовало несколько предпосылок для создания такого набора данных.

В Fashion-MNIST содержится 10 классов разной одежды по аналогии с 10 цифрами из MNIST. Подробное описание датасета можно найти далее

--------

## Fashion-MNIST description

**Content**

Each image is 28 pixels in height and 28 pixels in width, for a total of 784 pixels in total. Each pixel has a single pixel-value associated with it, indicating the lightness or darkness of that pixel, with higher numbers meaning darker. This pixel-value is an integer between 0 and 255. The training and test data sets have 785 columns. The first column consists of the class labels (see above), and represents the article of clothing. The rest of the columns contain the pixel-values of the associated image.

To locate a pixel on the image, suppose that we have decomposed x as x = i * 28 + j, where i and j are integers between 0 and 27. The pixel is located on row i and column j of a 28 x 28 matrix.
For example, pixel31 indicates the pixel that is in the fourth column from the left, and the second row from the top, as in the ascii-diagram below.


**Labels**

Each training and test example is assigned to one of the following labels:

0. T-shirt/top
1. Trouser
2. Pullover
3. Dress
4. Coat
5. Sandal
6. Shirt
7. Sneaker
8. Bag
9. Ankle boot


**TL;DR**

Each row is a separate image
Column 1 is the class label.
Remaining columns are pixel numbers (784 total).
Each value is the darkness of the pixel (1 to 255)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

dir_path = "/content/drive/My Drive/Colab Notebooks/Part-5/data/"

Mounted at /content/drive


## 1. Загружаем исходные данны и готовим их для классификации

In [9]:
#import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

#%matplotlib inline
np.set_printoptions(precision=3)
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (8, 6)

In [10]:
train = pd.read_csv(dir_path+"fashion-mnist_train.csv", sep=',', header= 0)
# train = pd.read_csv("./data/fashion-mnist_train.csv", sep=',')
train.shape

(60000, 785)

In [11]:
test = pd.read_csv(dir_path+"fashion-mnist_test.csv", sep=',', header= 0)
# test = pd.read_csv("./data/fashion-mnist_test.csv", sep=',', header= 0)
test.shape

(10000, 785)

In [12]:
# type(test)
# test.iloc[:,0
# test.drop(labels=[0,1], axis=1)
test.drop(labels="label", axis=1)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
0          0       0       0       0       0       0       0       9       8   
1          0       0       0       0       0       0       0       0       0   
2          0       0       0       0       0       0      14      53      99   
3          0       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
9995       0       0       0       0       0       0       0       0       0   
9996       0       0       0       0       0       0       0       0       0   
9997       0       0       0       0       0       0       0       0       0   
9998       0       1       3       0       0       0       0       0       0   
9999       0       0       0       0       0       0       0     140     119   

      pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
0           0  ...       103        87        56         0         0   
1           0  ...        34         0         0         0         0   
2          17  ...         0         0         0         0        63   
3         161  ...       137       126       140         0       133   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
9995       37  ...        32        23        14        20         0   
9996        0  ...         0         0         0         2        52   
9997        0  ...       175       172       172       182       199   
9998        0  ...         0         0         0         0         0   
9999      103  ...       111        95        75        44         1   

      pixel780  pixel781  pixel782  pixel783  pixel784  
0            0         0         0         0         0  
1            0         0         0         0         0  
2           53        31         0         0         0  
3          224       222        56         0         0  
4            0         0         0         0         0  
...        ...       ...       ...       ...       ...  
9995         0         1         0         0         0  
9996        23        28         0         0         0  
9997       222        42         0         1         0  
9998         1         0         0         0         0  
9999         0         0         0         0         0  

[10000 rows x 784 columns]

## 2. Подготовка данных для обработки
----------

In [13]:
# разделение меток и картинок на обучающей выборке
# X_train = train.drop(labels=0, axis=1)
X_train = train.drop(labels="label", axis=1)
y_train = train.iloc[:, 0]
X_train.shape, y_train.shape



((60000, 784), (60000,))

In [24]:
Xtrain = X_train.to_numpy().reshape(-1, 28, 28)
Xtrain.shape


(60000, 28, 28)

In [21]:
# разделение меток и картинок на обучающей выборке
# X_test = test.drop(labels=0, axis=1)
X_test = test.drop(labels="label", axis=1)
y_test = test.iloc[:, 0]
X_test.shape, y_test.shape

((10000, 784), (10000,))

In [25]:
Xtest = X_test.to_numpy().reshape(-1, 28, 28)
Xtest.shape

(10000, 28, 28)

In [27]:
# нормировка данных - здесь ВАШ КОД !!!

# x_train = X_train.astype('float32')
# x_test = X_test.astype('float32')
xtrain = Xtrain.astype('float32')
xtest = Xtest.astype('float32')

xtrain /= 255
xtest /= 255

print(xtrain.shape[0], 'train samples')
print(xtest.shape[0], 'test samples')

xtest

60000 train samples
10000 test samples


array([[[0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.016, ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.004, ..., 0.   , 0.   , 0.   ],
        ...,
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ]],

       [[0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        ...,
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ]],

       [[0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        ...,
        [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
        [0.   , 0.   , 0.   , ..., 0.   , 0. 

In [29]:
xtrain[3]

array([[0.   , 0.   , 0.   , 0.004, 0.008, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.447, 0.718, 0.439, 0.216, 0.09 , 0.282, 0.4  , 0.647,
        0.627, 0.11 , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.004, 0.   , 0.   , 0.094, 0.737,
        0.639, 0.365, 0.533, 0.6  , 0.659, 0.988, 0.682, 0.533, 0.651,
        0.51 , 0.482, 0.514, 0.259, 0.   , 0.   , 0.004, 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.008, 0.   , 0.039, 0.616, 0.847, 0.886,
        0.816, 0.557, 0.259, 0.451, 0.584, 0.902, 0.745, 0.769, 0.776,
        0.675, 0.871, 0.42 , 0.647, 0.827, 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.463, 0.839, 0.682, 0.659,
        0.427, 0.784, 0.486, 0.588, 0.561, 0.227, 0.247, 0.349, 0.537,
        0.38 , 0.659, 0.541, 0.557, 0.765, 0.612, 0.   , 0.   , 0.   ,
        0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.098, 0.549, 0.275, 0.314, 0.169,
        0.278



------

In [30]:
# переформатируем метки для решения задачи классификации ...
num_classes = 10
print(y_train[0])

ytrain = tf.keras.utils.to_categorical(y_train, num_classes)
ytest = tf.keras.utils.to_categorical(y_test, num_classes)


print(ytrain[0])

2
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [31]:
y_train[0]

2

## 3. Строим сверточную нейронную сеть
-------------

### **Моделируем нейросеть**

Смоделируем нейросеть с полносвязными слоями 

--------

In [32]:
from tensorflow.keras.layers import Dense, Dropout

In [35]:
# Convolutional
# Инициируем модель нейросети
model = tf.keras.models.Sequential()

# Конструируем нейросеть
model.add(tf.keras.layers.Input(shape=(28,28,1)))

model.add(tf.keras.layers.Convolution2D(filters=6, kernel_size=(5,5), activation="linear"))
model.add(tf.keras.layers.MaxPooling2D())

model.add(tf.keras.layers.Convolution2D(filters=16, kernel_size=(5,5), activation="linear"))
model.add(tf.keras.layers.MaxPooling2D())

model.add(tf.keras.layers.Convolution2D(filters=120, kernel_size=(4,4), activation="relu"))
model.add(tf.keras.layers.Flatten())

model.add(tf.keras.layers.Dense(84, activation="tanh"))
model.add(tf.keras.layers.Dense(num_classes, activation="softmax"))



<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7fa5971c4e80>>

In [36]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 24, 24, 6)         156       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 12, 12, 6)        0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 8, 8, 16)          2416      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 4, 4, 16)         0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 1, 1, 120)         30840     
                                                                 
 flatten (Flatten)           (None, 120)              

In [37]:
# Готовим модель для обучения
model.compile(
    loss = "categorical_crossentropy",
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics = ["accuracy"]
)

In [38]:
# Обучаем модель
batch_size = 256
epochs = 50

history = model.fit(
    xtrain, ytrain,
    batch_size = batch_size,
    epochs = epochs,
    verbose = 1,
    validation_data = (xtest, ytest)
)

Epoch 1/50
235/235 [==============================] - 24s 100ms/step - loss: 0.7489 - accuracy: 0.7325 - val_loss: 0.5268 - val_accuracy: 0.8055
Epoch 2/50
235/235 [==============================] - 24s 101ms/step - loss: 0.4817 - accuracy: 0.8207 - val_loss: 0.4600 - val_accuracy: 0.8273
Epoch 3/50
235/235 [==============================] - 23s 99ms/step - loss: 0.4157 - accuracy: 0.8489 - val_loss: 0.3852 - val_accuracy: 0.8592
Epoch 4/50
235/235 [==============================] - 23s 100ms/step - loss: 0.3694 - accuracy: 0.8656 - val_loss: 0.3569 - val_accuracy: 0.8690
Epoch 5/50
235/235 [==============================] - 24s 101ms/step - loss: 0.3426 - accuracy: 0.8753 - val_loss: 0.3293 - val_accuracy: 0.8794
Epoch 6/50
235/235 [==============================] - 23s 99ms/step - loss: 0.3239 - accuracy: 0.8800 - val_loss: 0.3381 - val_accuracy: 0.8783
Epoch 7/50
235/235 [==============================] - 24s 101ms/step - loss: 0.3072 - accuracy: 0.8868 - val_loss: 0.3097 - val_accu

На 30-й итерации обучение можно было завершить.
-----------

In [39]:
loss, accuracy = model.evaluate(xtest, ytest, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.36178478598594666
Test accuracy: 0.9021000266075134
