In [4]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')

from mpl_toolkits import mplot3d

In [5]:
user = np.array([10, 0, 0, 20, 0, 5])

user1 = np.array([20, 3, 0, 35, 0, 12])
user2 = np.array([9, 0, 3, 15, 0, 2])
user3 = np.array([2, 5, 3, 0, 10, 0])

dist_1 = np.linalg.norm(user - user1, ord=2)
dist_2 = np.linalg.norm(user - user2, ord=2)
dist_3 = np.linalg.norm(user - user3, ord=2)

print(round(dist_1, 3), round(dist_2, 3), round(dist_3, 3))

19.57 6.633 24.96


In [6]:
k = 0.05
ker = lambda d: np.exp(-k * d)

print(round(ker(dist_1), 3), round(ker(dist_2), 3), round(ker(dist_3), 3))

0.376 0.718 0.287


In [7]:
cos_1 = user @ user1 / np.linalg.norm(user, ord = 2) / np.linalg.norm(user1, ord=2)
cos_2 = user @ user2 / np.linalg.norm(user, ord = 2) / np.linalg.norm(user2, ord=2)
cos_3 = user @ user3 / np.linalg.norm(user, ord = 2) / np.linalg.norm(user3, ord=2)

print(round(cos_1, 3), round(cos_2, 3), round(cos_3, 3))


0.994 0.977 0.074


In [12]:
from sklearn.metrics.pairwise import cosine_similarity as cosine_sim

users = np.vstack([user, user1, user2, user3])
print(f'users = \n {users}')

S = cosine_sim(users)
print(f'users similarity = \n {np.round(S, 3)}')

users = 
 [[10  0  0 20  0  5]
 [20  3  0 35  0 12]
 [ 9  0  3 15  0  2]
 [ 2  5  3  0 10  0]]
users similarity = 
 [[1.    0.994 0.977 0.074]
 [0.994 1.    0.968 0.111]
 [0.977 0.968 1.    0.129]
 [0.074 0.111 0.129 1.   ]]
