In [ ]:
# 1
import numpy as np
a = np.array([1,2,3])
np.full(shape=(2,3), fill_value=a)

In [ ]:
#2
Amat = np.array([[1,2],[3,4], [5,6]])
print(Amat.shape)

In [ ]:
# 3
Amat = np.array([[1,2,3,4],[3,4,5,6], [5,6,7,8]])
print(Amat[:, [1,2]])

In [ ]:
# 4
Emat = np.eye(N=3)
Smat = Emat[:,:]
Emat += 1

print(Emat)
print(id(Emat))
print(Smat)
print(id(Smat))

print(id(Emat) == id(Smat))
print(Smat[0,0])

print(Emat.base)
print(Smat.base)

In [54]:
# 5
Amat = np.array([[1,2,3,4],[5,4,5,10], [5,6,7,8]])
bvect = np.array(range(4))
A1mat = Amat + bvect

print(A1mat)
print(A1mat[1,3])

[[ 1  3  5  7]
 [ 5  5  7 13]
 [ 5  7  9 11]]
13


In [55]:
# 6
Atab = np.array([[1,2,0], [4,5,1], [7,8,0], [10, 11, 1], [2,2,0]])
print(Atab[:,2]==1)

print((Atab[Atab[:,2]==1,0:2]))
print(sum(Atab[Atab[:,2]==1,0:2]))
sum(Atab[Atab[:,2]==1,0:2])[0]

[False  True False  True False]
[[ 4  5]
 [10 11]]
[14 16]


14

In [56]:
# 7
Atab = np.array([[1,2,0], [10,5,1], [7,5,0], [10, 11, 1], [2,2,0]])
Atab[Atab[:,2]==0,0:2].mean(axis=0)[1]

3.0

In [57]:
# 8
Atab = np.array([[5,2,0], [0,5,1], [7,7,0], [10, 11, 1], [4,2,0]])
print(Atab)
Btab = Atab[Atab[:,2] == 0]
print(Btab)
print(Btab[:,0].argsort())
Btab = Btab[Btab[:,0].argsort()]
print(Btab)
print(Btab[-1,0])



[[ 5  2  0]
 [ 0  5  1]
 [ 7  7  0]
 [10 11  1]
 [ 4  2  0]]
[[5 2 0]
 [7 7 0]
 [4 2 0]]
[2 0 1]
[[4 2 0]
 [5 2 0]
 [7 7 0]]
7


In [58]:
# 9
from numpy import linalg

Em = np.eye(6)
print(Em)

Bm = np.ones(shape=(6,6))
print(Bm)

Cm = Em + 9 * Bm
print(Cm)

print(linalg.eigvals(Cm))
print(max(linalg.eigvals(Cm)))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[10.  9.  9.  9.  9.  9.]
 [ 9. 10.  9.  9.  9.  9.]
 [ 9.  9. 10.  9.  9.  9.]
 [ 9.  9.  9. 10.  9.  9.]
 [ 9.  9.  9.  9. 10.  9.]
 [ 9.  9.  9.  9.  9. 10.]]
[ 1. 55.  1.  1.  1.  1.]
54.99999999999997


In [59]:
from statistics import mean


a1 = np.random.normal(loc=4, scale=2, size= 100_000)
print(a1.size)
a2 = a1**2

print(a2.mean())

100000
20.01329926160044
