In [8]:
import numpy as np
Cmat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(Cmat)

Cmat[2,3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


12

In [14]:
Cmat[0:2, 0:4:2]

array([[1, 3],
       [5, 7]])

In [18]:
Emat = np.eye(N=3)
ones_array = np.ones(shape=(3,3))

print(Emat)
print(ones_array)

Amat = Emat + ones_array
print(Emat + ones_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [20]:
print(Amat)
print(Emat)
print(Amat * Emat * 3)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[6. 0. 0.]
 [0. 6. 0.]
 [0. 0. 6.]]


In [22]:
print(Amat)
print(ones_array)
print(Amat @ ones_array)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]


In [23]:
l1 = np.array([1,2,3])
l2 = np.array([3,3,1])
print(l1 @ l2)


12


In [29]:
print(a := np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))
print(b := np.array([1,2,3,4]))
print(a @ b)

print(a.shape, b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 30  70 110]
(3, 4) (4,)


In [31]:
a = 'one'
b = 'one','two','three'

res = a if a not in b else None
print(res)




None


In [33]:
a = 'one'
b = 'one','two','three'

l = {x.upper() for x in b}
print(l)


{'TWO', 'ONE', 'THREE'}
