In [1]:
import numpy as np
np.set_printoptions(precision=4)
import matplotlib.pyplot as plt

In [22]:
r0 = np.array([-4, 4])
dr = np.array([1, -1])
alfa = np.arange(0, 7.1, 1, dtype=int)

print('r0:', r0)
print('dr:', dr)
print('alfa:', alfa)
print('r0.reshape((1, -1)):', r0.reshape((1, -1)))
print('dr.reshape((1, -1)):', dr.reshape((1, -1)))
print('alfa.reshape((-1, 1)):', alfa.reshape((-1, 1)))
print('alfa.reshape((-1, 1)) @ dr.reshape((1, -1)', alfa.reshape((-1, 1)) @ dr.reshape((1, -1)))

        # xy_arr = r0.reshape((1, -1)) + alfa.reshape((-1, 1)) @ dr.reshape((1, -1))


r0: [-4  4]
dr: [ 1 -1]
alfa: [0 1 2 3 4 5 6 7]
r0.reshape((1, -1)): [[-4  4]]
dr.reshape((1, -1)): [[ 1 -1]]
alfa.reshape((-1, 1)): [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
alfa.reshape((-1, 1)) @ dr.reshape((1, -1) [[ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]
 [ 4 -4]
 [ 5 -5]
 [ 6 -6]
 [ 7 -7]]
r0.reshape((1, -1)) + alfa.reshape((-1, 1)) @ dr.reshape((1, -1)) [[-4  4]
 [-3  3]
 [-2  2]
 [-1  1]
 [ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]]


In [23]:
print('r0.reshape((1, -1)) + alfa.reshape((-1, 1)) @ dr.reshape((1, -1))', r0.reshape((1, -1)) + alfa.reshape((-1, 1)) @ dr.reshape((1, -1)))


r0.reshape((1, -1)) + alfa.reshape((-1, 1)) @ dr.reshape((1, -1)) [[-4  4]
 [-3  3]
 [-2  2]
 [-1  1]
 [ 0  0]
 [ 1 -1]
 [ 2 -2]
 [ 3 -3]]


In [19]:
A = np.array([[1,2],[3,4], [5,6]])
B = np.array([[1,2,3],[4,5,6]])

print(A @ B)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [20]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([7, 8, 9, 10, 11, 12])

print(A @ B)

217
