In [7]:
import numpy as np
a1 = np.full(shape=(3,4), dtype=int, fill_value=5)
a2 = np.full(shape=(3,4), dtype=int, fill_value=3)

print("\n+\n", a1 + a2, sep='')
print("\n-\n", a1 - a2, sep='')
print("\n*\n", a1 * a2, sep='')
print("\n/\n", a1 / a2, sep='')


+
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]

-
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]

*
[[15 15 15 15]
 [15 15 15 15]
 [15 15 15 15]]

/
[[1.66666667 1.66666667 1.66666667 1.66666667]
 [1.66666667 1.66666667 1.66666667 1.66666667]
 [1.66666667 1.66666667 1.66666667 1.66666667]]


In [9]:
import numpy as np
a1 = np.full(shape=(3,4), dtype=int, fill_value=5)
a2 = np.full(shape=(3,4), dtype=int, fill_value=3)

print("\n+2\n", a1 + 2, sep='')
print("\n-2\n", a1 - 2, sep='')
print("\n*2\n", a1 * 2, sep='')
print("\n/2\n", a1 / 2, sep='')



+2
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

-2
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]

*2
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

/2
[[2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]]


In [16]:
import numpy as np
a1 = np.full(shape=(3,4), dtype=int, fill_value=5)
a2 = np.full(shape=(3,4), dtype=int, fill_value=3)

print("\n@2\n", a1 @ a2.T, "\n", sep='')

print(np.dot(a1, a2.T))



@2
[[60 60 60]
 [60 60 60]
 [60 60 60]]

[[60 60 60]
 [60 60 60]
 [60 60 60]]


In [19]:
import numpy as np

a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a1, "\n")
v1 = np.array([10, 20, 30, 40])
print(v1, "\n")

print(a1 + v1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[10 20 30 40] 

[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [20]:
import numpy as np

a1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a1, "\n")
v1 = np.array([[10], [20], [30]])
print(v1, "\n")

print(a1 + v1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[10]
 [20]
 [30]] 

[[11 12 13 14]
 [25 26 27 28]
 [39 40 41 42]]


In [34]:
import numpy as np

a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 4, 3, 2])

print(a1 == a2)

f = a1 >= a2
print("f =", f)
print(a1[f])
print(a2[~f])



[False False  True False]
f = [False False  True  True]
[3 4]
[5 4]


In [39]:
import numpy as np

a1 = np.array([1, 2, 3, 4])
a1[a1 % 2 == 1] = 10
print(a1)

a1 = np.array([1, 2, 3, 4])
a1[a1 % 2 == 1] *= 10
print(a1)

[10  2 10  4]
[10  2 30  4]


In [41]:
import numpy as np

l1 = np.array([1,0,1,0], dtype=bool)
l2 = np.array([0,0,1,1], dtype=bool)

print(np.logical_and(l1, l2))
print(np.logical_or(l1, l2))

[False False  True False]
[ True False  True  True]
