In [5]:
import numpy as np

a1 = np.arange(-50, 50, 0.01)
print(a1.size)

10000


In [10]:
import numpy as np

a1 = np.linspace(-50, 50, 1001)
print(a1.size, type(a1))
print(a1[:20])

1001 <class 'numpy.ndarray'>
[-50.  -49.9 -49.8 -49.7 -49.6 -49.5 -49.4 -49.3 -49.2 -49.1 -49.  -48.9
 -48.8 -48.7 -48.6 -48.5 -48.4 -48.3 -48.2 -48.1]


In [13]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1)
a1.reshape((3,-1))
a1.reshape((6,-1))

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
a1 = np.array(range(1, 29))
print(a1, "\n")

print(a1.reshape(-1, 7))
print(a1, "\n")

a2 = a1.reshape(-1, 7)
print(a2.flatten(),"\n")

print(a1)
a1.resize(4, 7)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28] 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [31]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a1, "\n")

print(sum(a1))
print(np.sum(a1))
print(np.mean(a1))
print(np.min(a1))
print(np.max(a1))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[15 18 21 24]
78
6.5
1
12


In [37]:
a1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a1, "\n")

print(a1.sum(axis=0))
print(a1.sum(axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[15 18 21 24]
[10 26 42]
