In [6]:
import numpy as np

print(np.random.sample())
print(np.random.sample((2,)))
print(np.random.sample((2,3)))

0.16641297548598188
[0.76478052 0.21548398]
[[0.98425536 0.04701667 0.07441447]
 [0.23717923 0.0432773  0.84906106]]


In [36]:
r = np.random.random(size=(100,10))
print(r.shape)

nums = np.random.choice(len(r), int(0.6 * len(r)), replace=False)
print(sorted(nums))

first = r[nums]
print(first.shape)

notnums = list(set(range(len(r))) - set(nums))
second = r[notnums]
print(second.shape)

(100, 10)
[0, 1, 2, 4, 5, 13, 14, 17, 19, 20, 22, 23, 24, 25, 27, 28, 29, 30, 33, 34, 36, 37, 38, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 55, 58, 59, 63, 64, 65, 66, 67, 68, 69, 71, 72, 76, 77, 78, 81, 84, 86, 87, 89, 92, 93, 95, 96, 99]
(60, 10)
(40, 10)


In [33]:
print(np.random.randint(1, 25, 15))
print(np.random.random_integers(1, 25, 15))

print(np.random.randint(1, 25, (5,10)))

[ 1 23 15  7  5  3  4 19 22 21  6  4 22 10 21]
[23 13 25  6 13 19  1 19 13  5 13 12 23 23 22]
[[21  6  3 13  4  2 16 22  8 22]
 [15  8  9 11  8  7 24  7  7  8]
 [10 23 18 23 20  5 11 12 16  9]
 [ 8  8 13  9  6 10  7 13  5 15]
 [ 9  2 21 10 13  1 23  5 11  6]]


C:\Users\SergeyVasin\AppData\Local\Temp\ipykernel_7316\2224495323.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 25 + 1) instead
  print(np.random.random_integers(1, 25, 15))


In [34]:
print(np.random.uniform(1, 25, (5,10)))


[[ 2.16079465  9.36594221 20.98268374 19.86096348 13.95416607 10.13748254
  13.2336462   5.04109547  8.03592902  5.57817917]
 [ 3.85957801  6.96285572 16.10080147 13.9773441  13.87068895  3.18715726
  23.86358147  3.79702633 12.544565   13.57100915]
 [ 4.95484082 17.61725611  8.04008217 24.23492028  2.33447429  8.73152364
  17.87351915  6.33872902  4.2530771   4.8120475 ]
 [16.33563238  3.39039916 24.47565325  8.93902663 20.53521137  6.74496367
   4.63757366  6.21703354 14.98976619 16.40430984]
 [ 3.17029265 22.86483361 10.19901784  3.47021766 13.65866082 17.54185679
  20.65475723  1.95236656 17.99887978 22.88919254]]


In [41]:
r = np.random.random(size=(100,10))

b = int(0.6 * len(r))

nums = np.array(range(len(r)))
print(nums)

np.random.shuffle(nums)
print(nums)

first = r[nums[:b]]
second = r[nums[b:]]

print(first.shape)
print(second.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[59 30 67 46 22 91 69 64  8 25 50 48  4 68 23 13 89 61 55 98 18 62 79 32
 28 14 49 29 95 47 88  3 33 97 76 93 38 60 77 34 84 35 53 41 20 39 56 66
 58 27  0 36 52 75 65 82 73  7 24 37 85 70 54 94 17 45 80 72 86 42 40  6
 10 19 21 12  2 83 16 57  5 63 11 78 92 74 87 90  1 43 71 44 96  9 15 81
 26 31 51 99]
(60, 10)
(40, 10)


In [63]:
np.random.seed(1000)
print(np.random.random(10))
np.random.seed()
print(np.random.random(10))

[0.65358959 0.11500694 0.95028286 0.4821914  0.87247454 0.21233268
 0.04070962 0.39719446 0.2331322  0.84174072]
[0.60133682 0.84495957 0.06837826 0.73653622 0.97122398 0.01446231
 0.41560459 0.82385223 0.55452873 0.32876375]
