# ndarray

In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(type(a))

# type of elements in the array
print(a.dtype)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int32


In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [5]:
import numpy as np

arr = np.array([1, '2', 3, 4])

print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U11


In [9]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [12]:
a1 = np.array([1,2,3])
a2 = a1.view()
a3 = a1.copy()

a1[2] = 4

print(a1)
print(a2)
print(a3)

print(a1.base)
print(a2.base)
print(a3.base)



[1 2 4]
[1 2 4]
[1 2 3]
None
[1 2 4]
None


In [13]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [15]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [29]:
import numpy as np

ar1 = np.zeros(shape=(3,4, 5), dtype=int)
# print(ar1)

ar2 = np.ones(shape=(5, 4, 3), dtype=float)
# print(ar2)
ar3 = np.full(shape = (5, 6), dtype = int, fill_value=15)
# print(ar3)

em = np.eye(5, dtype=int)
# print(em)

rr = np.random.random(size=(2,3))
print(rr)

[[0.83294145 0.63006418 0.68695608]
 [0.29741979 0.08186154 0.14483717]]


In [56]:
ar4 = np.full(shape = (2,3), dtype = int, fill_value= 15)
print(ar4)
print(ar4[:,:,np.newaxis])
print(ar4.shape)
print(ar4.dtype)
print(ar4.size)
print(ar4.itemsize)
print(ar4.size * ar4.itemsize, 'B')



[[15 15 15]
 [15 15 15]]
[[[15]
  [15]
  [15]]

 [[15]
  [15]
  [15]]]
(2, 3)
int32
6
4
24 B


In [65]:
rr = np.random.random(size=(2,3,4))
print(rr, "\n\n")

for i in range(rr.shape[2]):
    print(rr[:,:,i])

[[[0.23552075 0.47970583 0.54951578 0.44002246]
  [0.92778192 0.3815379  0.76388889 0.59679901]
  [0.97819664 0.33936391 0.29726175 0.21233919]]

 [[0.37686915 0.4430862  0.79161883 0.25850384]
  [0.6284281  0.76830713 0.46063222 0.4264124 ]
  [0.18083882 0.75658503 0.54096105 0.80867957]]] 


[[0.23552075 0.92778192 0.97819664]
 [0.37686915 0.6284281  0.18083882]]
[[0.47970583 0.3815379  0.33936391]
 [0.4430862  0.76830713 0.75658503]]
[[0.54951578 0.76388889 0.29726175]
 [0.79161883 0.46063222 0.54096105]]
[[0.44002246 0.59679901 0.21233919]
 [0.25850384 0.4264124  0.80867957]]


In [81]:
rr = np.random.random(size=(2,3,4))
print(rr, "\n\n")

print(rr[1, (0,2)], "\n\n")

print(rr[1, (0,2), [1,2]], "\n\n")

print(rr[1, :, [1,2]])

[[[0.21803176 0.62668017 0.34924175 0.902874  ]
  [0.06952214 0.0944335  0.42839098 0.54157442]
  [0.69186264 0.01667109 0.664632   0.02369762]]

 [[0.78629469 0.03736246 0.16418656 0.53864661]
  [0.4709437  0.00626923 0.30604781 0.30762796]
  [0.60002623 0.2156587  0.13223115 0.0389741 ]]] 


[[0.78629469 0.03736246 0.16418656 0.53864661]
 [0.60002623 0.2156587  0.13223115 0.0389741 ]] 


[0.03736246 0.13223115] 


[[0.03736246 0.00626923 0.2156587 ]
 [0.16418656 0.30604781 0.13223115]]
