In [8]:
import numpy as np
from numpy import linalg as lna

a1 = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])
a2 = lna.inv(a1)

print(a1)
print(a2)
print(np.round(a1 @ a2, decimals=2))

print(lna.det(a1))

[[2 4 0 4 1]
 [2 4 1 1 0]
 [1 1 1 2 2]
 [0 1 3 2 4]
 [2 2 2 0 2]]
[[-0.6   0.4   1.6  -0.6  -0.1 ]
 [ 0.9  -0.6  -1.9   0.4   0.65]
 [-1.7   1.8   2.7  -0.2  -1.45]
 [-0.7   0.8   1.7  -0.2  -0.95]
 [ 1.4  -1.6  -2.4   0.4   1.4 ]]
[[ 1.  0.  0.  0.  0.]
 [-0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
19.99999999999999


In [35]:
a1 = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])
b = np.ones((a1.shape[0],))

print(a1)
print(b)

x = lna.solve(a1, b)
print(x)

x2 = lna.lstsq(a1, b, rcond=None)
print(x2)


[[2 4 0 4 1]
 [2 4 1 1 0]
 [1 1 1 2 2]
 [0 1 3 2 4]
 [2 2 2 0 2]]
[1. 1. 1. 1. 1.]
[ 0.7  -0.55  1.15  0.65 -0.8 ]
(array([ 0.7 , -0.55,  1.15,  0.65, -0.8 ]), array([], dtype=float64), 5, array([9.16608227, 4.74575513, 2.90119199, 1.00954799, 0.15697753]))


tuple

In [23]:
a1 = np.eye(4)
v = np.ones((1, a1.shape[1]))
h = np.ones((a1.shape[0],1))
print(a1)
print(v)
print(h)
print(np.hstack([a1, h]))
print(np.vstack([a1, v]))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 1. 1. 1.]]
[[1.]
 [1.]
 [1.]
 [1.]]
[[1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [40]:
a1 = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])

print(lna.det(a1))


a2 = np.array([[1,-1,-1,0],[-1,2,-1,-1],[-1,-1,2,-1],[0,-1,-1,1]])
print(lna.eigvals(a2))

19.99999999999999
[-1.  1.  3.  3.]
