## Практикум 2.1. Оптимизация ФОП

**Задание**

Дана функция одной переменной `f(a) = a4+ k1*a3 - k2*a2+ a - 1`  и начальная точка  `x0`.

Необходимо найти точку минимума с заданной точностью по производной `epsg`.

Для этого вы должны:

1. Задать оптимизируемую функцию как функцию от параметров **k1**, **k2**:
`optfun(x, k1, k2)`

2. Реализовать простой градиентный спуск в точку минимума как функцию параметров **x0**, **epsg**, **alfa**, **k1**, **k2**, **maxiter**:

`gradsteps(x0, epsg, alfa, k1, k2, maxiter)`

На выходе функция оптимизации `gradsteps(x0, epsg, alfa, k1, k2, maxiter)` должна возвращать список всех полученных приближений,
начиная с начального значения x0 и завершая полученным решением задачи. 

**maxiter** - ограничивает кол-во итераций, т.е. список не должен превышать `maxiter + 1` элемент.

Например, результатом обращения `gradsteps(x0=4, epsg=0.5, alfa=0.01, k1=3, k2=20, maxiter=100)`

должен быть список:

[4,   1.59,   1.828,   2.004,   2.112,   2.169,   2.195,   2.206]

In [31]:
import numpy as np
np.set_printoptions(suppress=True)

In [32]:
# --- Эту функцию программирует обучающийся!!! ----
def optfun(x, k1=3, k2=20):
    # задаем вычисление оптимизируемой функции 
    f = x**4 + k1*x**3 - k2*x**2 + x - 1
    return f
 
# --- Эту функцию программирует обучающийся!!! ----
# maxiter - ограничивает кол-во итераций, 
# т.е. список не должен превышать maxiter+1 элемент !
def gradsteps(x0, epsg=0.1, alfa=0.01, k1=3, k2=20, maxiter=100):
    # организуем градиентный спуск 
    xlist = [x0]
    nf = 0
    dx = 1e-7
    dfdx = (optfun(x0 + dx, k1, k2) - optfun(x0, k1, k2)) / dx
    while abs(dfdx) > epsg:
        x0 = x0 - alfa*dfdx
        dfdx = (optfun(x0 + dx, k1, k2) - optfun(x0, k1, k2)) / dx
        xlist.append(x0)
        nf += 1
        if nf > 100:
            break
    return xlist

#### Tests

In [33]:
dx = 1e-7
def dfx(x, k1, k2):
    return (optfun(x + dx, k1, k2) - optfun(x, k1, k2)) / dx


In [34]:
# test 0
# [4,   1.59,   1.828,   2.004,   2.112,   2.169,   2.195,   2.206]
res = gradsteps(x0=4, epsg=0.5, alfa=0.01, k1=3, k2=20, maxiter=100)
print(np.round(res, 3))

[4.    1.59  1.828 2.004 2.112 2.169 2.195 2.206]


In [35]:
def fu(x):
    return x**4 + x**3 - 10*x**2 + x - 1
def dfu(x):
    return 4*x**3 + 3*x**2 - 20*x + 1

dfu(-4)

-127

In [36]:
# test 1
# 1, 10, -4, 0.5, 0.02
# [-4.0, -1.46, -1.94292512, -2.3798357878958205, -2.6133086694230263, -2.660612372136513]
x0 = -4; epsg = 0.5; alfa = 0.02; k1 = 1; k2 = 10

res = gradsteps(x0=x0, epsg=epsg, alfa=alfa, k1=k1, k2=k2, maxiter=100)

result = [[r, optfun(r, k1, k2), dfx(r, k1, k2)] for r in res]
print(np.round(result, 3))

[[  -4.      27.    -127.   ]
 [  -1.46   -22.344   24.146]
 [  -1.943  -33.777   21.846]
 [  -2.38   -41.418   11.674]
 [  -2.613  -43.114    2.365]
 [  -2.661  -43.173    0.112]]


In [37]:
# test 2
# 1, 10, -5, 0.5, 0.02
# [-5.0, 1.4800000000000004, 1.6612326400000004, 1.7733845784004223, 1.8278764776818137, 1.849984935289558]
x0 = -5; epsg = 0.5; alfa = 0.02; k1 = 1; k2 = 10

res = gradsteps(x0=x0, epsg=epsg, alfa=alfa, k1=k1, k2=k2, maxiter=100)

result = [[r, optfun(r, k1, k2), dfx(r, k1, k2)] for r in res]
print(np.round(result, 3))


[[  -5.     244.    -324.   ]
 [   1.48   -13.384   -9.062]
 [   1.661  -14.735   -5.608]
 [   1.773  -15.208   -2.725]
 [   1.828  -15.313   -1.105]
 [   1.85   -15.33    -0.406]]


In [38]:
# test 3
# 2, 15, -4, 0.5, 0.01
x0 = -4; epsg = 0.5; alfa = 0.01; k1 = 2; k2 = 15

res = gradsteps(x0=x0, epsg=epsg, alfa=alfa, k1=k1, k2=k2, maxiter=100)

result = [[r, optfun(r, k1, k2), dfx(r, k1, k2)] for r in res]
print(np.round(result, 3))


[[  -4.    -117.     -39.   ]
 [  -3.61  -124.348   -0.691]
 [  -3.603 -124.35    -0.119]]


In [39]:
# test 4
# 2, 15, -5, 0.1, 0.01
x0 = -5; epsg = 0.1; alfa = 0.01; k1 = 2; k2 = 15

res = gradsteps(x0=x0, epsg=epsg, alfa=alfa, k1=k1, k2=k2, maxiter=100)

result = [[r, optfun(r, k1, k2), dfx(r, k1, k2)] for r in res]
print(np.round(result, 3))


[[  -5.      -6.    -199.   ]
 [  -3.01  -112.368   36.577]
 [  -3.376 -122.388   16.769]
 [  -3.543 -124.213    4.672]
 [  -3.59  -124.345    0.941]
 [  -3.6   -124.35     0.17 ]
 [  -3.601 -124.351    0.03 ]]


In [40]:
# test 5
# 3, 20, 5, 0.1, 0.01
x0 = 5; epsg = 0.1; alfa = 0.01; k1 = 3; k2 = 20

res = gradsteps(x0=x0, epsg=epsg, alfa=alfa, k1=k1, k2=k2, maxiter=100)

result = [[r, optfun(r, k1, k2), dfx(r, k1, k2)] for r in res]
print(np.round(result, 3))

[[   5.     504.     526.   ]
 [  -0.26    -2.66    11.938]
 [  -0.379   -4.401   17.252]
 [  -0.552   -8.055   25.145]
 [  -0.803  -15.85    36.869]
 [  -1.172  -32.589   53.805]
 [  -1.71   -67.649   75.719]
 [  -2.467 -133.218   94.4  ]
 [  -3.411 -220.822   83.397]
 [  -4.245 -270.416   26.975]
 [  -4.515 -273.78    -3.09 ]
 [  -4.484 -273.817    0.679]
 [  -4.491 -273.819   -0.142]
 [  -4.489 -273.819    0.03 ]]
