## Практикум 1.2. Оценка вектора градиента

Требуется реализовать функцию оценки градиента (вектора частных производных):

def eval_grad(f, r, dx=1e-5):
**ВХОД**:
- f - функция n переменных; n=2, 3, ..
- r = (r[0], .., r[n-1]) - начальная точка (кортеж размерности n);
- dx - используемый шаг для оценки производной вдоль каждого из направлений;

ВЫХОД:
- вектор градиента g = (g[0], .., g[n-1]) в виде np.array() (с точностью до 4-го знака после запятой)

---

**ПРИМЕР 1**

ВХОД 
f(r) = r[0]**2 + 4 * r[1]**2
r = (-3.0, 2.0)

ВЫХОД
array([-6., 16.])
---

**ПРИМЕР 2**

ВХОД 
f(r) = r[0]**2 + 2 * r[1]**2 + 3 * r[2]**2
r = (-3.0, 2.0, 1.0)

ВЫХОД
array([-6., 4., 2.])

In [21]:
import numpy as np

# Этот модуль программирует обучающийся!
def eval_grad(f, r, dx=1e-5):
    """ функция оценки вектора градиента
    f - адрес функции нескольких переменных f(r)
    r - tuple """
    dfdx = []
    # здесь ваш код 
    
    for i in range(len(r)):
        x = []
        for j in range(len(r)):
            if i == j:
                x.append(r[j] + dx)
            else:
                x.append(r[j])
        dfdx.append(np.round((f(x) - f(r)) / dx, 4))

    return np.array(dfdx)

#### Test

In [22]:
def f(r):
    return r[0]**2 + 4 * r[1]**2
r = (-3.0, 2.0)
# array([-6., 16.])

eval_grad(f, r)

array([-6., 16.])

In [23]:
def f(r):
    return r[0]**2 + 2 * r[1]**2 + 3 * r[2]**2
r = (-3.0, 2.0, 1.0)
# array([-6., 4., 2.])

eval_grad(f, r)

array([-6.,  8.,  6.])