# Text

Практикум 2.1. Оптимизация методом покоординатного спуска

Тип работы:  Индивидуальная работа

Данное задание выполняется после того, как вы успешно справились с заданиями по реализации алгоритма градиентного спуска вдоль направления:
`def opt1D(f1, x0, alpha, epsg=0.1, maxsteps=10)`

и вычисления градиента функции нескольких переменных
`def eval_grad(f, r0, dx=1e-8)`

Теперь требуется написать функцию, которая будет использовать обе эти функции и будет реализовать метод покоординатного спуска (см. лекционный материал)

`def coord2D(f, r0, alpha=0.01, epsg=0.1, maxsteps=100)`

**ВХОД**:
- `f` - функция n переменных; n=2, 3, ..
- `r0 = (r01, .., r0n)` - начальная точка (кортеж размерности n);
- `alpha` - коэффициент шага градиентного спуска вдоль направления;
- `epsg` - требуемая точность искомого приближения т.минимума по производной;
- `maxsteps` - максимальное количество итераций;

**ВЫХОД**:
- `r = (r1, .., rn)` в виде **np.array()** (с точностью до 4-го знака после запятой) - приближение, найденное методом покоординатного спуска или с заданной точностью по градиенту (**|g(r)| < epsg**) или после **maxsteps** шагов.

Под шагом в данном случае подразумевается поиск вдоль направления. Т.е. поиск вдоль оси OX будет одним шагом, вдоль оси OY будет другим шагом, ...

ВАЖНО!
> Точность, с которой нужно находить минимум вдоль выбранного направления должна быть меньше, чем epsg; поэтому берем ее равной 0.5*epsg.
> При одномерном спуске вдоль направления всегда задавайте ограничение по кол-ву шагов = 10 (maxsteps=10) !

---

**ПРИМЕР 1**

**ВХОД**

`f(r) = r[0]**2+4*r[1]**2`

`r0 = (-3.0, 2.0)`

`rlist = coord2D(f, r0, alpha=0.1, maxsteps=10)`

`print(rlist[-1])`

**ВЫХОД**

`array([-0.0366  0.0009])`

---

**ПРИМЕР 2**

**ВХОД**

`f(r) = .5*(1 - x[0])**2 + (x[1] - x[0]**2)**2`

`r0 = (-1.0, 2.0)`

`rlist = coord2D(f, r0, alpha=0.1, maxsteps=10)`

`print(rlist[-1])`

**ВЫХОД**

`array([-0.5483  0.7067])`


# Code

In [23]:
printv = False
# Этот модуль программирует обучающийся!
import numpy as np
from numpy.linalg import norm

""" генерация функции вдоль направления dr из точки r0 """
def make_1Dfun(f, r0, dr):
    def f1D(x0, f=f, r0=r0, dr=dr):
        r0 = np.array(r0, dtype=float)
        dr = np.array(dr, dtype=float)
        r = r0 + x0 * dr
        return f(r)
    return f1D

# ====== эти функции слушатель берет из предыдущих заданий ======
'''
""" антиградиентный спуск вдоль направления """
def opt1D(f1, x0, alpha, epsg=0.1, maxsteps=10):
    dx = 1e-7
    steps = 0
    return x0, steps
'''
""" антиградиентный спуск """
def opt1D(f1, x0, alpha, epsg=0.1, maxsteps=10):
    dx = 1e-7
    step = 0
    dfdx = (f1(x0 + dx) - f1(x0)) / dx

    if printv:
        print('Start:', f1(x0), dfdx)

    while (abs(dfdx) > epsg) and (step < maxsteps):
        x0 = x0 - alpha * dfdx
        dfdx = (f1(x0 + dx) - f1(x0)) / dx

        if printv:
            print(step, f1(x0), dfdx)

        step += 1
    return x0#, iter
'''
""" оценка вектора градиента функции f в точке r0 """
def eval_grad(f, r, dx=1e-5):
    """
    f - адрес функции нескольких переменных f(r)
    r - tuple """
    dfdx = []
    # здесь ваш код 
    # ...
    return np.array(dfdx)
'''
# оценка вектора градиента функции f в точке r0
def eval_grad(f, r, dx=1e-5):
    dfdx = []
    x = np.array(r, dtype=float)

    for i in range(len(x)):
        mdx = np.zeros(len(x))
        mdx[i] = dx
        dfdx.append((f(x+mdx) - f(x)) / dx)

    return np.array(dfdx)
# ==========================================================
'''
# реализация метода покоординатного спуска
def coord2D(f, r0, alpha=0.01, epsg=0.1, maxsteps=10):
    """
    f - адрес функции нескольких переменных f(r)
    r0 - начальная точка (n-мерный кортеж) 
    alpha - коэффициент шага градиентного спуска вдоль направления;
    epsg - требуемая точность искомого приближения т.минимума по градиенту;
    maxsteps - максимальное количество шагов покоординатного спуска;
    """
    epsg1 = epsg / 2    # точность спуска по проивзодной вдоль направления
    maxsteps1 = 10      # ограничение по кол-ву шагов при одномерном спуске
    rlist = [r0]
    step = 0
    # далее ваш код
    # ...
    
    return rlist
'''
# реализация метода покоординатного спуска
def coord2D(f, r0, alpha = 0.01, epsg = 0.1, maxsteps = 10):
    """
    f - адрес функции нескольких переменных f(r)
    r0 - начальная точка (n-мерный кортеж) 
    alpha - коэффициент шага градиентного спуска вдоль направления;
    epsg - требуемая точность искомого приближения т.минимума по градиенту;
    maxsteps - максимальное количество шагов покоординатного спуска;
    """
    epsg1 = epsg / 2    # точность спуска по производной вдоль направления
    maxsteps1 = 10      # ограничение по кол-ву шагов при одномерном спуске
    r0 = np.array(r0, dtype=float)
    rlist = [r0]
    step = 0
    grad = eval_grad(f, r0)

    while (norm(grad, ord=2) > epsg) and (step < maxsteps):
        dr = np.zeros(len(r0))
        dr[step % len(r0)] = 1
        f1 = make_1Dfun(f, r0, dr)

        if printv:
            print(f'I (direction): {step % len(r0)}')

        opt1 = opt1D(f1, 0.0, alpha, epsg=epsg1, maxsteps=maxsteps1)
        r0 = r0 + dr * opt1
        rlist.append(r0)
        step += 1
        grad = eval_grad(f, r0)

        if printv:
            print(f(r0), grad, norm(grad, ord=2))
    return rlist


# Release

In [ ]:
# Этот модуль программирует обучающийся!
import numpy as np
from numpy.linalg import norm

""" генерация функции вдоль направления dr из точки r0 """
def make_1Dfun(f, r0, dr):
    def f1D(x0, f=f, r0=r0, dr=dr):
        r0 = np.array(r0, dtype=float)
        dr = np.array(dr, dtype=float)
        r = r0 + x0 * dr
        return f(r)
    return f1D

# ====== эти функции слушатель берет из предыдущих заданий ======
def opt1D(f1, x0, alpha, epsg=0.1, maxsteps=10):
    dx = 1e-7
    step = 0
    dfdx = (f1(x0 + dx) - f1(x0)) / dx

    while (abs(dfdx) > epsg) and (step < maxsteps):
        x0 = x0 - alpha * dfdx
        dfdx = (f1(x0 + dx) - f1(x0)) / dx
        step += 1

    return x0

# оценка вектора градиента функции f в точке r0
def eval_grad(f, r, dx=1e-5):
    dfdx = []
    x = np.array(r, dtype=float)

    for i in range(len(x)):
        mdx = np.zeros(len(x))
        mdx[i] = dx
        dfdx.append((f(x+mdx) - f(x)) / dx)

    return np.array(dfdx)

# реализация метода покоординатного спуска
def coord2D(f, r0, alpha = 0.01, epsg = 0.1, maxsteps = 10):
    """
    f - адрес функции нескольких переменных f(r)
    r0 - начальная точка (n-мерный кортеж) 
    alpha - коэффициент шага градиентного спуска вдоль направления;
    epsg - требуемая точность искомого приближения т.минимума по градиенту;
    maxsteps - максимальное количество шагов покоординатного спуска;
    """
    epsg1 = epsg / 2    # точность спуска по производной вдоль направления
    maxsteps1 = 10      # ограничение по кол-ву шагов при одномерном спуске
    r0 = np.array(r0, dtype=float)
    rlist = [r0]
    step = 0
    grad = eval_grad(f, r0)

    while (norm(grad, ord=2) > epsg) and (step < maxsteps):
        dr = np.zeros(len(r0))
        dr[step % len(r0)] = 1

        f1 = make_1Dfun(f, r0, dr)
        opt1 = opt1D(f1, 0.0, alpha, epsg=epsg1, maxsteps=maxsteps1)

        r0 = r0 + dr * opt1
        rlist.append(r0)
        step += 1
        grad = eval_grad(f, r0)

    return rlist


# Tests

In [22]:

def f(r):
    return r[0]**2+4*r[1]**2

r0 = (-3.0, 2.0)
rlist = coord2D(f, r0, alpha=0.1, maxsteps=10)
rlist
# print(rlist[-1])


# array([-0.0366  0.0009])

array([[-3.        ,  2.        ],
       [-0.25769808,  2.        ],
       [-0.25769808,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995],
       [-0.02213614,  0.00319995]])

In [24]:
def f(x):
    return 0.5*(1 - x[0])**2 + (x[1] - x[0]**2)**2
r0 = (-1.0, 2.0)
rlist = coord2D(f, r0, alpha=0.1, maxsteps=10)
rlist

# print(rlist[-1])
# array([-0.5483  0.7067])

[(-1.0, 2.0),
 array([-1.24880005,  2.        ]),
 array([-1.24880005,  1.59734005]),
 array([-1.05121791,  1.59734005]),
 array([-1.05121791,  1.14734565]),
 array([-0.76276935,  1.14734565]),
 array([-0.76276935,  0.63039557]),
 array([0.2109191 , 0.63039557]),
 array([0.2109191, 0.094816 ]),
 array([0.53737089, 0.094816  ]),
 array([0.53737089, 0.26794205])]

# Tests 2

In [ ]:
1
-3.0, 2.0
0.1, 4