## Обучение нейрона (VPL)

Тип работы:  Индивидуальная работа

Ваша задача - запрограммировать методы класса Logneuron с использованием правила Видроу-Хоффа так, чтобы нейрон смог обучиться на внешних данных моделировать булевы операции...

Для обучения нейрона следует использовать алгоритм, который приведен в уроке 6.6. Обучение нейрона с использованием градиентного спуска (ВИДЕО).


ВХОД для ИНИЦИАЛИЗАЦИИ ОБЪЕКТА:

```python
# num_features - размерность входа в нейрон (без учета нейрона сдвига)

# eta, t_max - коэфф-т обучения нейрона и максимальное кол-во шагов обучения

# обучение self.w, self.b на выборке X с метками y
def fit(self, X, y, random_state=42):
   pass

# прогноз модели на выборке X
def predict(self, X):
   ym = ...
   return ym
```

ПРИМЕР.

В качестве данных будет использоваться выборка данных для задачи классификации цветков Ириса с помощь функции из sklearn.datasets.

`num_features=4`


Для входных параметров `eta=0.1, t_max=10` 

Должна быть достигнута точность классификации на тестовой выборке >= 0,71

In [265]:
import numpy as np

# этот модуль программирует обучающийся !!!

class Logneuron:
    
    # инициализация объекта нейрон
    # num_features - размерность входа в нейрон (без учета нейрона сдвига)
    # eta, t_max - коэфф-т обучения нейрона и максимальное кол-во шагов обучения
    def __init__(self, num_features, eta, t_max, random_state=42):
        np.random.seed(random_state)
        self.b = 0
        self.eta = eta
        self.w = np.random.random(num_features) - 0.5
        self.t_max = t_max
        self.t = 0
    
    # обучение self.w, self.b на выборке X с метками y
    def fit(self, X, y, random_state=42):
        # np.random.seed(random_state)
        # ... обучение нейрона на выборке X с метками y
        print(f'Prediction: {self.predict(X=X)}')
        for step in range(self.t_max):
            print(f'\nStep: {step}')
            u = self.getValues(X=X)
            print(f'u: {np.round(u, 6)}')

            ym = self.getActivationValues(u=u)
            print(f'ym: {np.round(ym, 6)}')

            diff = self.getDifference(y=y, ym=ym)
            print(f'Diff: {np.round(diff, 6)}')

            grad = self.getGradient(X=X, diff=diff)
            print(f'Gradient: {grad}')

            self.b += self.eta * grad[0]
            self.w += self.eta * grad[1:]
            print(f'New W: {np.round((self.b, *self.w), 6)}')
            print(f'New prediction: {self.predict(X=X)}')
        # for step in range(self.t_max):
        #     ym = []
        #     ydiff = []
        #     gr = []
        #     for i in range(X.shape[0]):
        #         res = self.b * 1.0
        #         for j in range(X.shape[1]):
        #             res += self.w * X[i, j]
        #         ym.append(self.sigmoid(res))
        #         ydiff.append(y[i] - ym[i])
        #         ydiffn = np.array(ydiff)

        #     ydiffsum = np.sum(ydiffn)
        #     self.b = self.b + self.eta * 2 * ydiffsum / (X.shape[0])

        #     for j in range(X.shape[1]):
        #         res = 0
        #         for i in range(X.shape[0]):
        #             res += ydiffn[i] * X[i, j]
        #         gr.append(2*res/(X.shape[0]))
        #     grn = np.array(gr)
        #     self.w = self.w + self.eta * grn

    # def get_class(self, y):
    #     return 1 if y >= 0.5 else 0

    def get_class(self, ym):
        return np.array([1 if x >=0.5 else 0 for x in ym])
        # label = []
        # # ... определение метки класса (0 или 1) по выходу нейросети ym
        # for i in range(len(ym)):
        #     if ym[i] >= 0.5:
        #         label.append(1)
        #     else:
        #         label.append(0)
        # return label
    
    # # прогноз модели на выборке X
    # def predict(self, X):
    #     ym = None
        
    #     # ... программируем прогноз модели ...
    #     label = self.get_class(ym)
    #     return label

    # прогноз модели на выборке X
    def predict(self, X):
        ym = self.getActivationValues(self.getValues(X=X))
        return self.get_class(ym=ym)
        # ym = []
        # for i in range(X.shape[0]):
        #     res = self.b * 1.0
        #     for j in range(X.shape[1]):
        #         res += self.w[j] * X[i, j]
        #     ym.append(self.sigmoid(res))
        # label = self.get_class(ym)
        # return label

        # # ym = np.sign(self.w @ np.array([1.0, *X]))
        # return ym

    def getGradient1(self, X, diff):
        xlines = X.shape[0]
        xcolumns = X.shape[1]
        result = [2 * np.sum(diff) / xlines]
        for j in range(xcolumns):
            r = 0.0
            for i in range(xlines):
                r += diff[i] * X[i, j]
            result.append(2 * r / xlines)
        return np.array(result)

    def getGradient(self, X, diff):
        xlines = X.shape[0]
        xcolumns = X.shape[1]
        result = [np.sum(diff)]
        for j in range(xcolumns):
            xc = np.array(X[:,j])
            result.append(diff @ xc)
        return np.array(result) * 2 / xlines

    def getDifference(self, y, ym):
        y = np.array(y)
        ym = np.array(ym)
        return y - ym

    def getActivationValues1(self, u):
        r = []
        for i in range(u.shape[0]):
            r.append(1 / (1 + np.exp(-u[i])))
        return np.array(r)

    def getActivationValues(self, u):
        return 1 / (1 + np.exp(-u))

    def getValues1(self, X):
        xlines = X.shape[0]
        xcolumns = X.shape[1]
        us = []
        for i in range(xlines):
            r = self.b * 1.0
            for j in range(xcolumns):
                r += X[i,j] * self.w[j]
            us.append(r)
        usn = np.array(us)
        return usn

    def getValues(self, X):
        xlines = X.shape[0]
        us = []
        for i in range(xlines):
            xi = np.array(X[i])
            us.append(self.b + xi @ self.w)
        return np.array(us)

    def selftest(self, case=3):
        print(f'NumFeatures: {self.w.shape[0]} Eta: {self.eta}, TMax: {self.t_max}')
        print(f'W: {np.round((self.b, *self.w), 6)}')

        X = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
        print(f'X: {X}')
        y = np.array([0, 0, 1])
        print(f'y: {y}')

        values = self.getValues(X=X)
        print(f'Values  : {np.round(values, 6)}')
        # valuesnp = self.getValuesNP(X=X)
        # print(f'ValuesNP: {np.round(valuesnp, 6)}')

        activationValues = self.getActivationValues(u=values)
        print(f'ActivationValues  : {np.round(activationValues, 6)}')
        # activationValuesNP = self.getActivationValuesNP(u=values)
        # print(f'ActivationValuesNP: {np.round(activationValuesNP, 6)}')

        difference = self.getDifference(y=y, ym=activationValues)
        print(f'Difference: {np.round(difference, 6)}')
        # print(f'Sum(Difference): {np.sum(difference)}')

        gradient = self.getGradient(X=X, diff=difference)
        print(f'Gradient:  {gradient}')

        # gradient1 = self.getGradient1(X=X, diff=difference)
        # print(f'Gradient1: {gradient1}')

        prediction = self.predict(X)
        print(f'Prediction: {prediction}')

        # print(X[:,0])
        # print(difference @ X[:,0])

        print('\nFIT:')
        self.fit(X=X, y=y)

#### Test

In [266]:
# 3
a = Logneuron(num_features=3, eta=0.1, t_max=50, random_state=42)
a.selftest()

NumFeatures: 3 Eta: 0.1, TMax: 50
W: [ 0.       -0.12546   0.450714  0.231994]
X: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
y: [0 0 1]
Values  : [0.147195 0.31437  0.481544]
ActivationValues  : [0.536732 0.577951 0.618112]
Difference: [-0.536732 -0.577951  0.381888]
Gradient:  [-0.4885309  -0.01168835 -0.06054144 -0.10939453]
Prediction: [1 1 1]

FIT:
Prediction: [1 1 1]

Step: 0
u: [0.147195 0.31437  0.481544]
ym: [0.536732 0.577951 0.618112]
Diff: [-0.536732 -0.577951  0.381888]
Gradient: [-0.4885309  -0.01168835 -0.06054144 -0.10939453]
New W: [-0.048853 -0.126629  0.44466   0.221054]
New prediction: [1 1 1]

Step: 1
u: [0.093732 0.255458 0.417184]
ym: [0.523416 0.563519 0.602809]
Diff: [-0.523416 -0.563519  0.397191]
Gradient: [-4.59829772e-01  1.89442840e-04 -4.57935344e-02 -9.17765116e-02]
New W: [-0.094836 -0.12661   0.440081  0.211877]
New prediction: [1 1 1]

Step: 2
u: [0.044082 0.201687 0.359291]
ym: [0.511019 0.550251 0.588869]
Diff: [-0.511019 -0.550251  0.411131]
Grad

In [267]:
l1 = [1,2,3]
l2 = [4,5,6]
k=3
print(l1 + k*l2)

n1 = np.array(l1)
n2 = np.array(l2)
print(n1 + k*n2)


[1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6]
[13 17 21]


In [268]:
# predicate = 
int((1>=0.5))

aa = np.array([0.5, 0.3, 0.7])
# np.array((aa >=0.5), dtype=int)
np.array([1 if x >=0.5 else 0 for x in aa])

array([1, 0, 1])

In [269]:
difference

NameError: name 'difference' is not defined