## Обучение нейрона (VPL)

Тип работы:  Индивидуальная работа

Ваша задача - запрограммировать методы класса Logneuron с использованием правила Видроу-Хоффа так, чтобы нейрон смог обучиться на внешних данных моделировать булевы операции...

Для обучения нейрона следует использовать алгоритм, который приведен в уроке 6.6. Обучение нейрона с использованием градиентного спуска (ВИДЕО).


ВХОД для ИНИЦИАЛИЗАЦИИ ОБЪЕКТА:

```python
# num_features - размерность входа в нейрон (без учета нейрона сдвига)

# eta, t_max - коэфф-т обучения нейрона и максимальное кол-во шагов обучения

# обучение self.w, self.b на выборке X с метками y
def fit(self, X, y, random_state=42):
   pass

# прогноз модели на выборке X
def predict(self, X):
   ym = ...
   return ym
```

ПРИМЕР.

В качестве данных будет использоваться выборка данных для задачи классификации цветков Ириса с помощь функции из sklearn.datasets.

`num_features=4`


Для входных параметров `eta=0.1, t_max=10` 

Должна быть достигнута точность классификации на тестовой выборке >= 0,71

In [6]:
import numpy as np

# этот модуль программирует обучающийся !!!

class Logneuron:
    
    # инициализация объекта нейрон
    # num_features - размерность входа в нейрон (без учета нейрона сдвига)
    # eta, t_max - коэфф-т обучения нейрона и максимальное кол-во шагов обучения
    def __init__(self, num_features, eta, t_max, random_state=42):
        np.random.seed(random_state)
        self.b = 0
        self.eta = eta
        self.w = np.random.random(num_features) - 0.5
        self.t_max = t_max
        self.t = 0
    
    # обучение self.w, self.b на выборке X с метками y
    def fit(self, X, y, random_state=42):
        # ... обучение нейрона на выборке X с метками y
        for step in range(self.t_max):
            u = self.getValues(X=X)
            ym = self.getActivationValues(u=u)
            diff = self.getDifference(y=y, ym=ym)
            grad = self.getGradient(X=X, diff=diff)

            self.b += self.eta * grad[0]
            self.w += self.eta * grad[1:]

    def get_class(self, ym):
        return np.array([1 if x >=0.5 else 0 for x in ym])

    # прогноз модели на выборке X
    def predict(self, X):
        ym = self.getActivationValues(self.getValues(X=X))
        return self.get_class(ym=ym)

    def getGradient(self, X, diff):
        xlines = X.shape[0]
        xcolumns = X.shape[1]
        result = [np.sum(diff)]
        for j in range(xcolumns):
            xc = np.array(X[:,j])
            result.append(diff @ xc)
        return np.array(result) * 2 / xlines

    def getDifference(self, y, ym):
        y = np.array(y)
        ym = np.array(ym)
        return y - ym

    def getActivationValues(self, u):
        return 1 / (1 + np.exp(-u))

    def getValues(self, X):
        xlines = X.shape[0]
        us = []
        for i in range(xlines):
            xi = np.array(X[i])
            us.append(self.b + xi @ self.w)
        return np.array(us)


#### Test

In [7]:
# 3
a = Logneuron(num_features=3, eta=0.1, t_max=50, random_state=42)


print(f'NumFeatures: {a.w.shape[0]} Eta: {a.eta}, TMax: {a.t_max}')
print(f'W: {np.round((a.b, *a.w), 6)}')

X = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
print(f'X: {X}')
y = np.array([0, 0, 1])
print(f'y: {y}')

values = a.getValues(X=X)
print(f'Values  : {np.round(values, 6)}')

activationValues = a.getActivationValues(u=values)
print(f'ActivationValues  : {np.round(activationValues, 6)}')

difference = a.getDifference(y=y, ym=activationValues)
print(f'Difference: {np.round(difference, 6)}')

gradient = a.getGradient(X=X, diff=difference)
print(f'Gradient:  {gradient}')

prediction = a.predict(X)
print(f'Prediction: {prediction}')


a.fit(X=X, y=y)
prediction2 = a.predict(X)
print(f'Prediction2: {prediction2}')

NumFeatures: 3 Eta: 0.1, TMax: 50
W: [ 0.       -0.12546   0.450714  0.231994]
X: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
y: [0 0 1]
Values  : [0.147195 0.31437  0.481544]
ActivationValues  : [0.536732 0.577951 0.618112]
Difference: [-0.536732 -0.577951  0.381888]
Gradient:  [-0.4885309  -0.01168835 -0.06054144 -0.10939453]
Prediction: [1 1 1]
Prediction2: [0 0 1]


In [8]:
l1 = [1,2,3]
l2 = [4,5,6]
k=3
print(l1 + k*l2)

n1 = np.array(l1)
n2 = np.array(l2)
print(n1 + k*n2)


[1, 2, 3, 4, 5, 6, 4, 5, 6, 4, 5, 6]
[13 17 21]
